project 'FirebaseExplorer.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebaseExplorer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirebaseExplorer
  pod 'SwiftLint'
  pod 'Firebase/Core'

  target 'FirebaseExplorerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FirebaseExplorerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
